server:
  port: ${SERVER_PORT:8083}

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/SMS
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: password
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
